---
title: "Account Processing"
author: "Greg Sanders"
date: "December 16, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(plyr)
require(ggplot2)
require(scales)
# options(java.parameters = "-Xmx8g")
require(XLConnect)
#require(reshape2)
require(data.table)

# Path<-"K:/2007-01 PROFESSIONAL SERVICES/R scripts and data/"
# Path<-"D:/Users/Greg Sanders/Documents/Development/R-scripts-and-data/"
Path<-"C:/Users/gsand_000.ALPHONSE/Documents/Development/R-scripts-and-data/"
source(paste(Path,"lookups.r",sep=""))
source(paste(Path,"helper.r",sep=""))


SourceFolderList<-c("FY2012","FY2013", "FY2014","FY2015","FY2016","FY2017")#"FY2011",



ComptrollerMelt<-function(dfComptroller){
  varlist<-c("SourceFiscalYear",
             "AccountDSI",
             "Account",
             "MilDeptDW",
             "AccountTitle",
             "Account.Title", 
             "Organization" ,
             "BudgetActivity",
             "BudgetActivityTitle",
             "BudgetSubActivity",
             "BudgetSubActivityTitle",
              "BudgetLineItem", 
             "StateCountry",
             "StateCountryTitle",
             "Fiscal.Year",
             "FacilityCategoryTitle",
             "LocationTitle",
             "ConstructionProject",
             "ConstructionProjectTitle",
             "AGtitle",
             "BSA",
             "BSAtitle",
             "BSA.Title"  ,
             "LineNumber",
             "LineItem",
             "LineItemTitle",
             "ProgramElement",
             "ProgramElementTitle",
             "CostType",
             "CostTypeTitle",
             "LineNumber",
             "SAG",
             "SAGtitle",
             "SAG.Title", 
             "IncludeInTOA",
             "AddOrNonAdd",
             "Classified",
             "BudgetType", 
             "FiscalYear",
             "SubActivity", 
      # "ComptrollerVariable",
          "Project.Title", 
          "Treasury.Agency", 
             "SourceType",
             "OriginType"
       
  )
  
  varlist<-varlist[varlist %in% colnames(dfComptroller) ]
  data.table::melt(dfComptroller,
       id.vars=varlist
  )
  
}

ComptrollerVariableRename<-function(dfComptroller){
  if(!"FiscalYear" %in% colnames(dfComptroller)){
    dfComptroller$FiscalYear<-as.numeric(
      substring(as.character(dfComptroller$variable),4,7))
    dfComptroller$variable<-substring(as.character(dfComptroller$variable),9,999)
    # dfComptroller$variable<-substring(as.character(dfComptroller$variable),1,999)
  }
  dfComptroller<-read_and_join(
    ""
    ,"RenameComptrollerColumns.csv"
    ,dfComptroller
  )   
  
  
  if(any(is.na(dfComptroller$AllColumns))){
    stop(paste("Unaccounted for Comptroller Column Variant(s): ",
               paste(unique(dfComptroller$variable[is.na(dfComptroller$AllColumns)]),
                     collapse=", "),
               sep=", "))
  }
  
  varlist<-c("SourceFiscalYear",
             "AccountDSI",
             "Account",
             "MilDeptDW",
             "AccountTitle",
             "Account.Title", 
             "Organization" ,
             "BudgetActivity",
             "BudgetActivityTitle",
             "BudgetSubActivity",
             "BudgetSubActivityTitle",
             "BudgetLineItem", 
             "StateCountry",
             "StateCountryTitle",
             "Fiscal.Year",
             "FacilityCategoryTitle",
             "LocationTitle",
             "ConstructionProject",
             "ConstructionProjectTitle",
             "AGtitle",
             "BSA",
             "BSAtitle",
             "BSA.Title",
             "LineNumber",
             "LineItem",
             "LineItemTitle",
             "ProgramElement",
             "ProgramElementTitle",
             "CostType",
             "CostTypeTitle",
             "LineNumber",
             "SAG",
             "SAGtitle",
             "SAG.Title", 
             "IncludeInTOA",
             "AddOrNonAdd",
             "Classified",
             "BudgetType",
             "FiscalYear",
              "Project.Title", 
             "Treasury.Agency", 
             "SourceType", 
             "TOAamount", 
             
             "OriginType"
             
             #Note that origin type is missing in the other function, as it's added in this step.
  )
  
  varlist<-varlist[varlist %in% colnames(dfComptroller) ]
  subset(dfComptroller,select=-c(variable,SourceColumn,AllColumns))
  dfComptroller<-reshape2::dcast(dfComptroller, 
                                 paste(
                                   paste(varlist,collapse=" + ")
                                   ,"~  Consolidate"),
                                 sum, 
                                 fill=NA_real_ )
  
  
  dfComptroller
}

ComptrollerOCObyAccount<-function(dfComptroller){
  dfComptroller<-ddply(dfComptroller,
                       .(AccountDSI,
                         AccountTitle,
                         Organization,
                         SourceFiscalYear,
                         FiscalYear,
                         OriginType),
                       plyr::summarise,
                       EnactedType=sum(EnactedType)
  )
  dfComptroller<-subset(dfComptroller,!is.na(EnactedType))
  dfComptroller<-reshape2::dcast(dfComptroller, 
                                 AccountDSI +
                                   AccountTitle +
                                   Organization +
                                   SourceFiscalYear +
                                   FiscalYear ~  
                                   OriginType,
                                 sum, 
                                 fill=NA_real_ )
  dfComptroller$pOCO=dfComptroller$OCO/(dfComptroller$OCO+dfComptroller$Base)
  dfComptroller
}

ComptrollerLoadWorkbook<-function(sfy,fileprefix){
  if(file.exists(file.path("Data",sfy,paste(fileprefix,"1a.xlsx",sep="")))){
    ReturnXLS <- XLConnect::loadWorkbook(file.path("Data",sfy,paste(fileprefix,"1a.xlsx",sep="")))
  }
  else if(file.exists(file.path("Data",sfy,paste(fileprefix,"1a.xls",sep="")))) {
    ReturnXLS <- XLConnect::loadWorkbook(file.path("Data",sfy,paste(fileprefix,"1a.xls",sep="")))
  }
  else if(file.exists(file.path("Data",sfy,paste(fileprefix,"1.xlsx",sep="")))) {
    ReturnXLS <- XLConnect::loadWorkbook(file.path("Data",sfy,paste(fileprefix,"1.xlsx",sep="")))
  }
  else if(file.exists(file.path("Data",sfy,paste(fileprefix,"1.xls",sep="")))) {
    ReturnXLS <- XLConnect::loadWorkbook(file.path("Data",sfy,paste(fileprefix,"1.xls",sep="")))
  }
  
  ReturnXLS
}

```






##Military Personnel Programs (M-1)
```{r MilPers}
# Load workbook MilPers
for(sfy in SourceFolderList){
  NumericFiscalYear<-as.numeric(substring(sfy,3,7))#Drop the FY from FY20XX
  MilPersXLS <- ComptrollerLoadWorkbook(sfy,"m")

  MilPersData <- readWorksheet(MilPersXLS, sheet = 1, header=TRUE,startRow=2)
  MilPersData<-standardize_variable_names(Path,MilPersData)
  
  colnames(MilPersData)[colnames(MilPersData)=="Account"]<-"AccountDSI"
  colnames(MilPersData)
  MilPersData$SourceFiscalYear<-NumericFiscalYear
  MilPersData<-ComptrollerMelt(MilPersData)
  MilPersData<-ComptrollerVariableRename(MilPersData)
  write.csv(MilPersData,file.path("Data",sfy,"Output",paste("MilPers(",NumericFiscalYear,").csv",sep="")))
}

```


##Operation and Maintenance Programs (0-1)
```{r OnM}
# Load workbook o1
for(sfy in SourceFolderList){
  NumericFiscalYear<-as.numeric(substring(sfy,3,7))#Drop the FY from FY20XX

    OnMXLS <- ComptrollerLoadWorkbook(sfy,"o")
  
  OnMdata <- readWorksheet(OnMXLS, sheet = 1, header =TRUE,startRow=2)
  OnMdata<-standardize_variable_names(Path,OnMdata)
  
  colnames(OnMdata)[colnames(OnMdata)=="Account"]<-"AccountDSI"
  colnames(OnMdata)
  
  OnMdata$SourceFiscalYear<-NumericFiscalYear
  OnMdata<-ComptrollerMelt(OnMdata)
  
  OnMdata$value = as.numeric(OnMdata$value)
  
  OnMdata<-ComptrollerVariableRename(OnMdata)
  
  write.csv(OnMdata,file.path("Data",sfy,"Output",paste("OnM(",NumericFiscalYear,").csv",sep="")))
  
}

```

##Revolving and Management Fund (RF-1)

```{r RevolvingFunds}
# Load workbook RF
for(sfy in SourceFolderList){
  NumericFiscalYear<-as.numeric(substring(sfy,3,7))#Drop the FY from FY20XX

    RFXLS <- ComptrollerLoadWorkbook(sfy,"rf")
  
  RFdata <- readWorksheet(RFXLS, sheet = 1, header =TRUE, startRow=2)
  RFdata<-standardize_variable_names(Path,RFdata)
  colnames(RFdata)[colnames(RFdata)=="Account"]<-"AccountDSI"
  colnames(RFdata)
  RFdata$SourceFiscalYear<-NumericFiscalYear
  RFdata<-ComptrollerMelt(RFdata)
  RFdata<-ComptrollerVariableRename(RFdata)
  
  write.csv(RFdata,file.path("Data",sfy,"Output",paste("RF(",NumericFiscalYear,").csv",sep="")))
  
}  

```

##Procurement Programs Reserve Components (P-1R)

```{r Procurement}
# # debug(create_procedural_graphs
# Procurement <- read.xlsx2("./Data/p1_FY2017.xlsx", 
#                             sheetName = "Exhibit P-1",
#                             startRow=2)
# 
# Procurement$SourceFiscalYear<-2017
# Procurement<-standardize_variable_names(Path,Procurement)
# colnames(Procurement)[colnames(Procurement)=="Account"]<-"AccountDSI"


for(sfy in SourceFolderList){
  NumericFiscalYear<-as.numeric(substring(sfy,3,7))#Drop the FY from FY20XX
  
  ProcXLS <- ComptrollerLoadWorkbook(sfy,"p")
  
  ProcData <- readWorksheet(ProcXLS, sheet = 1, header =TRUE, startRow=2)
  ProcData<-standardize_variable_names(Path,ProcData)
  
  colnames(ProcData)[colnames(ProcData)=="Account"]<-"AccountDSI"
  colnames(ProcData)
  ProcData$SourceFiscalYear<-NumericFiscalYear
  ProcData<-ComptrollerMelt(ProcData)
  ProcData<-ComptrollerVariableRename(ProcData)
  # write.csv(ProcData,file.path("Data","Proc(2011).csv"))
  
  
  ProcurementsqlColumns<-c("ID"  ,
                           "SourceFiscalYear"  ,
                           "AccountDSI"  ,
                           "TreasuryAgencyCode"  ,
                           "MainAccountCode"  ,
                           "AccountTitle"  ,
                           "Organization"  ,
                           "BudgetActivity"  ,
                           "BudgetActivityTitle"  ,
                           "LineNumber" ,
                           "BSA"   ,
                           "BSA.Title"  ,
                           "LineItem"  ,
                           "LineItemTitle"  ,
                           "CostType"  ,
                           "CostTypeTitle"  ,
                           "AddOrNonAdd"  ,
                           "Classified"  ,
                           "Category"  ,
                           "FiscalYear"  ,
                           "OriginType" ,
                           "PBtotal" ,
                           "PBtype"  ,
                           "EnactedTotal"  ,
                           "EnactedType"  ,
                           "SpecialType"  ,
                           "ActualTotal"  ,
                           "QuantPBtotal"  ,
                           "QuantPBtype"  ,
                           "QuantEnactedTotal"  ,
                           "QuantEnactedType"  ,
                           "QuantSpecialTotal"  ,
                           "QuantActualTotal"  
  ) 
  
  Missing<-ProcurementsqlColumns[!ProcurementsqlColumns %in% colnames(ProcData)]
  ProcData[,Missing]<-NA
  
  ProcData<-ProcData[,ProcurementsqlColumns]
 
  
  # write.csv(ProcData,file.path("Data","P1_2011_Consolidated.csv"),
   write.csv(ProcData,file.path("Data",sfy,"Output",paste("Proc(",NumericFiscalYear,").csv",sep="")),
            row.names=FALSE,
            na="")
  # str(ProcData)
}
```
##Research Development, Test & Evaluation Programs (R-1)

```{r RDTE}

# 
# RnD <- read.xlsx2("./Data/r1_display_FY2017.xlsx", 
#                             sheetName = "Exhibit R-1",
#                             startRow=2)
# 
# RnD$SourceFiscalYear<-2017


for(sfy in SourceFolderList){
  NumericFiscalYear<-as.numeric(substring(sfy,3,7))#Drop the FY from FY20XX
  
  RDTEXLS <- ComptrollerLoadWorkbook(sfy,"r")
  
  
  # RDTEXLS <- loadWorkbook(file.path("Data","FY2011","r1.xls"))
  RDTEdata <- readWorksheet(RDTEXLS, sheet = 1 , header =TRUE,startRow=2)
  RDTEdata<-standardize_variable_names(Path,RDTEdata)
  
  colnames(RDTEdata)[colnames(RDTEdata)=="Account"]<-"AccountDSI"
  colnames(RDTEdata)
  RDTEdata$SourceFiscalYear<-NumericFiscalYear
  RDTEdata<-ComptrollerMelt(RDTEdata)
  RDTEdata<-ComptrollerVariableRename(RDTEdata)
  write.csv(RDTEdata,file.path("Data",sfy,"Output",paste("RDTE(",NumericFiscalYear,").csv",sep="")),
            row.names=FALSE,
            na="")
  
  
  
  RDTEsqlColumns<-c("ID"
                    ,"SourceFiscalYear"
                    ,"AccountDSI"
                    ,"TreasuryAgencyCode"
                    ,"MainAccountCode"
                    ,"AccountTitle"
                    ,"Organization"
                    ,"BudgetActivity"
                    ,"BudgetActivityTitle"
                    ,"LineNumber"
                    ,"ProgramElement"
                    ,"ProgramElementTitle"
                    ,"IncludeInTOA"
                    ,"Classified"
                    ,"FiscalYear"
                    ,"OriginType"
                    ,"PBtotal"
                    ,"PBtype"
                    ,"EnactedTotal"
                    ,"EnactedType"
                    ,"SpecialType"
                    ,"ActualTotal") 
  
  
  Missing<-RDTEsqlColumns[!RDTEsqlColumns %in% colnames(RDTEdata)]
  RDTEdata[,Missing]<-NA
  RDTEdata<-RDTEdata[,RDTEsqlColumns]
}
```

##Military Construction, Family Housing, and Base Realignment and Closure Program (C-1)  
```{r MilCon}



for(sfy in SourceFolderList){
  NumericFiscalYear<-as.numeric(substring(sfy,3,7))#Drop the FY from FY20XX
  
  # library(data.table)
  
  # debug(ComptrollerVariableRename)
  # Load workbook MilCon
  MilConXLS <- ComptrollerLoadWorkbook(sfy,"c")
 
  getSheets(MilConXLS)
  MilConData<-NULL
  # MilConData[,"Disaster Relief"] <- NULL
  # MilConData[,"Base Request"] <- NULL
  for(s in getSheets(MilConXLS)){
    SheetData <- readWorksheet(MilConXLS, sheet = s, header=TRUE,startRow=2)
    SheetData$sheet<-s
    # file_list <- (c(MilConData, SheetData))
    # rbindlist(lapply( file_list, fread ), fill = TRUE)
    MilConData<-rbind.fill(MilConData,SheetData)
  }
  rm(SheetData)
  colnames(MilConData)[colnames(MilConData)=="Fiscal.Year"]<-"FiscalYear"
  # MilConData$FiscalYear<-as.numeric(substring(as.character(MilConData$sheet),4,7))
  MilConData$variable<-substring(as.character(MilConData$sheet),9,999)
  
  #We should probably check more than one field just to be safe
  MilConData<-subset(MilConData,!is.na(FiscalYear))
  
  #Why is there a FiscalYear
  sheetlist<-unique(data.frame(FiscalYear=MilConData$FiscalYear,
                               variable=MilConData$variable))
  sheetlist<-ddply(sheetlist,
                   .(FiscalYear),
                   transform,
                   Count=length(FiscalYear))
  
  sheetlist$FiscalYear<-FactorToNumber(sheetlist$FiscalYear)
  sheetlist$ComptrollerVariable[sheetlist$FiscalYear==min(sheetlist$FiscalYear,na.rm=TRUE)] <- "PB.Amount"
  sheetlist$ComptrollerVariable[sheetlist$FiscalYear== max(sheetlist$FiscalYear,na.rm=TRUE)] <- "Actual.Amount"
  sheetlist$ComptrollerVariable[sheetlist$FiscalYear>min(sheetlist$FiscalYear,na.rm=TRUE) &
                                  sheetlist$FiscalYear<max(sheetlist$FiscalYear,na.rm=TRUE)] <- "Enacted.Amount"
  
  
  
  sheetlist$OriginType[sheetlist$variable=="OCO_Req"]<-"OCO"
  sheetlist$OriginType[sheetlist$variable=="OCO_Enacted"]<-"OCO"
  sheetlist$OriginType[sheetlist$variable=="B" ]<-"Total"#& sheetlist$Count==1
  # sheetlist$OriginType[sheetlist$variable=="" & sheetlist$Count==1]<-"Total"
  # sheetlist$OriginType[sheetlist$variable=="" & sheetlist$Count==2]<-"Base"
  sheetlist$ComptrollerVariable<-
    paste(sheetlist$OriginType,sheetlist$ComptrollerVariable,sep=".")
  
  # sheetlist <- sheetlist %>% select(-variable)
  
  # names(sheetlist)[names(sheetlist)=="variable1"] <- "variable"
  
  # These are already included via sheet so we don't need this anymore
  # MilConData <- MilConData %>% select(-variable)
  
  # MilConData$sheet <- gsub("(.*)(2.*)","\\2",MilConData$sheet)
  
  sheetlist<-sheetlist[,c("FiscalYear","variable", "OriginType","ComptrollerVariable")]
  
  MilConData<-join(MilConData, sheetlist, by = c("FiscalYear","variable"))
  
  # MilConData <- MilConData %>% select(-variable)
  MilConData <- MilConData[,!names(MilConData) %in% c("variable", "sheet")]
  
  # MilConData <- MilConData[-grep("variable", colnames(MilConData))]
  
  ########## Removed this because I suspect you don't want it to do what
  ########## it is doing.  Which is read the FY 2016 sheet, flag all those
  ########## entries as SourceType <- "OCO" (I doubt they are), and
  ########## bind them onto MilConData (which already contained 2016). -LCL
  # ------------------------------------------------------------------------
  # MilConData$SourceType<-'Base'
  # MilConDataOCO <- readWorksheet(MilConXLS, sheet = "FY 2016", header=TRUE, startRow=2)
  # MilConDataOCO$SourceType<-'OCO'
  # MilConData<-rbindlist(list(MilConData,MilConDataOCO), fill = TRUE) 
  # rm(MilConDataOCO)
  
  # ------------------------------------------------------------------------
  
  # added: drop a duplicative column that chokes the melt function
  # MilConData <- MilConData[,names(MilConData) != "variable"]
  
  
  MilConData<-standardize_variable_names(Path,MilConData)
  
  colnames(MilConData)
  MilConData$SourceFiscalYear<-NumericFiscalYear
  
  
  MilConData<-
    ComptrollerMelt(MilConData)
  
  
  
  names(MilConData)[names(MilConData)=="variable"] <- "BudgetMetric"
  names(MilConData)[names(MilConData)=="ComptrollerVariable"] <- "variable"
  colnames(MilConData)[colnames(MilConData)=="Fiscal.Year"]<-"FiscalYear"
  
  MilConData[is.na(MilConData)] <- 0 
  
  ######### part of comptrollerrename function that fails
  # dfComptroller$variable<-substring(as.character(dfComptroller$variable),9,999)
  # substring(as.character(MilConData$variable),1,999)
  # debug(ComptrollerVariableRename)
  MilConData<-ComptrollerVariableRename(MilConData)
  # write.csv(MilConData,file.path("Data","MilCon(2011).csv"))
  write.csv(RFdata,file.path("Data",sfy,"Output",paste("MilCon(",NumericFiscalYear,").csv",sep="")))
  
}


```

```{r OCOsum}
OCOsum<-ComptrollerOCObyAccount(MilPersData)
OCOsum<-rbind(OCOsum,ComptrollerOCObyAccount(OnMdata))
OCOsum<-rbind(OCOsum,ComptrollerOCObyAccount(RFdata))
OCOsum<-rbind(OCOsum,ComptrollerOCObyAccount(ProcData))
OCOsum<-rbind(OCOsum,ComptrollerOCObyAccount(RDTEdata))
```