---
title: "Crisis Funding Exploration"
author: "Greg Sanders"
date: "March 28, 2017"
output:
  html_document: 
  keep_md: yes
pdf_document: default
---
  
#Setup
```{r setup, include=FALSE}

library(plyr)
library(dplyr)
library(reshape2)
library(Hmisc)
library(csis360)
library(scales)

# Path<-"K:\\2007-01 PROFESSIONAL SERVICES\\R scripts and data\\"
# Path<-"C:\\Users\\Greg Sanders\\SkyDrive\\Documents\\R Scripts and Data SkyDrive\\"
Path<-"C:\\Users\\gsand_000.ALPHONSE\\Documents\\Development\\R-scripts-and-data\\"
source(paste(Path,"lookups.r",sep=""))
source(paste(Path,"helper.r",sep="")) 

# diigtheme1:::diiggraph()

Coloration<-read.csv(
  paste(Path,"Lookups\\","lookup_coloration.csv",sep=""),
  header=TRUE, sep=",", na.strings="", dec=".", strip.white=TRUE, 
  stringsAsFactors=FALSE
)

Coloration<-ddply(Coloration
                  , c(.(R), .(G), .(B))
                  , transform
                  , ColorRGB=as.character(
                    if(min(is.na(c(R,G,B)))) {NA} 
                    else {rgb(max(R),max(G),max(B),max=255)}
                  )
)


axis.text.size<-10
strip.text.size<-10
legend.text.size<-8
# table.text.size<-5.75
title.text.size<-12
geom.text.size<-12

main.text.size<-1
note.text.size<-1.40


load(
     file="Defense_budget_SP_LocationVendorCrisisFundingHistoryBucketCustomerDetail.Rdata")

```

#Decision Tree
#Step 1: Direct Crisis Labels 
##Step 1A: Is this an ARRA labled contract (or a CSIS labeled one)
```{r Step1A}
full_data<-replace_nas_with_unlabeled(full_data,"ContractCrisisFunding")
full_data<-replace_nas_with_unlabeled(full_data,"Is.Defense")
defense_data<-replace_nas_with_unlabeled(defense_data,"ContractCrisisFunding")


full_data$CrisisFunding<-"Unlabeled"
full_data$CrisisFunding<-ordered(full_data$CrisisFunding,levels=c("OCO","Disaster","ARRA","Unlabeled"))
full_data$CrisisFunding[full_data$CrisisFunding=="Unlabeled"]<-
  full_data$ContractCrisisFunding[full_data$CrisisFunding=="Unlabeled"]


Tree1A<-LatticePlotWrapper(
  VAR.color.legend.label="ARRA/CSIS Labeled Contract",
  VAR.main.label="",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=full_data,
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="CrisisFunding", #VAR.y.series
  VAR.facet.primary= "ContractCrisisFunding", #VAR.facet.primary
  VAR.facet.secondary="Is.Defense", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
              , scales="free_y" #The scales actually do stay fixed
              , space="fixed")
  
Tree1A

ggsave("Output//Tree1A.png", Tree1A, width=6.5, height= 3, units="in",dpi=300)
```

##Step 1B: Contingency or Humanitarian Peacekeeping Operation
```{r Step1B}
full_data<-replace_nas_with_unlabeled(full_data,"ContractCrisisFunding")
full_data<-replace_nas_with_unlabeled(full_data,"Theater")
full_data<-replace_nas_with_unlabeled(full_data,"contingencyhumanitarianpeacekeepingoperationText")
full_data$contingencyhumanitarianpeacekeepingoperationText[
  full_data$contingencyhumanitarianpeacekeepingoperationText=="Not Applicable"]<-"Unlabeled"


defense_data<-replace_nas_with_unlabeled(defense_data,"Theater")

# ConHumIsOCOcrisisFunding=1
# ,[ContingencyHumanitarianPeacekeepingOperation]

Tree1B<-LatticePercentLineWrapper(
  VAR.color.legend.label="Classification As of Prior Step",
  VAR.main.label="",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Percent of Obligations",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(full_data,Theater!="Unlabeled"),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="contingencyhumanitarianpeacekeepingoperationText", #VAR.y.series
  VAR.facet.primary= "Theater", #VAR.facet.primary
  # VAR.facet.secondary="contingencyhumanitarianpeacekeepingoperationText", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+theme(legend.position="bottom")+
  scale_x_date(
            # breaks=date_breaks("5 years"),
            labels=date_format("'%y"))
  
# +facet_grid(primary ~ secondary
#               , scales="free_y" #The scales actually do stay fixed
#               , space="fixed")

Contradictions1B<-LatticePlotWrapper(
  VAR.color.legend.label="Classification",
  VAR.main.label="",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(full_data,Theater!="Unlabeled"),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="CrisisFunding", #VAR.y.series
  VAR.facet.primary="contingencyhumanitarianpeacekeepingoperationText", #VAR.facet.primary
  VAR.facet.secondary= "Theater", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
              , scales="free_y" #The scales actually do stay fixed
              , space="fixed")+
  theme(legend.position="bottom")


Tree1B
Contradictions1B

ggsave("Output//Tree1B.png", Tree1B, width=6.5, height= 3, units="in",dpi=300)
ggsave("Output//Tree1Bcontradictions.png", Contradictions1B, width=6.5, height= 4.5, units="in",dpi=300)

full_data$CrisisFunding[full_data$CrisisFunding=="Unlabeled" & full_data$ConHumIsOCOcrisisFunding==1]<-"OCO"

```



##Step 1C: National Action Interest Code
```{r Step1C}
full_data<-replace_nas_with_unlabeled(full_data,"NIAcrisisFunding")
defense_data<-replace_nas_with_unlabeled(defense_data,"NIAcrisisFunding")
full_data<-replace_nas_with_unlabeled(full_data,"NIAcrisisFunding")

#       ,[nationalinterestactioncode]
#Flipping so first element is on top

labels.x.DF<-prepare_labels_and_colors(full_data,"nationalinterestactioncodeText")
      full_data$NIAlist<-factor(full_data$nationalinterestactioncodeText,
        levels=c(rev(labels.x.DF$variable)),
        labels=c(rev(labels.x.DF$Label)),
        ordered=TRUE)
  
        
Tree1CdetailIsDefense<-LatticePlotWrapper(
  VAR.color.legend.label="National Interest Action",
  VAR.main.label="",
  VAR.X.label="", #"Fiscal Year",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(full_data,NIAcrisisFunding !="Unlabeled"
                     | nationalinterestactioncodeText=="Inauguration 2009"),
  # NA, #VAR.ncol
  VAR.x.variable="NIAlist", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="Is.Defense" #VAR.y.series
  # VAR.facet.primary=NA , #"NIAcrisisFunding", #VAR.facet.primary
  # VAR.facet.secondary=NA,  # VAR.facet.secondary=NA
  # MovingAverage=0,
  # MovingSides=1,
  # DataLabels=FALSE
  # "Is.Defense"
  #                       ,VAR.override.coloration=NA
)+ theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  coord_flip()+theme(legend.position="bottom")

write.csv(subset(full_data, nationalinterestactioncodeText=="California Wildfires 2008") ,"Output//CaliforniaWildfires.csv")


#Remove the premature Californnia Wildfire 
full_data$NIAcrisisFunding[
  full_data$nationalinterestactioncodeText=="California Wildfires 2008" &
    full_data$Fiscal.Year<as.Date("2008-01-01")
]<-"Unlabeled"

Tree1Ctheater<-LatticePercentLineWrapper(
  VAR.color.legend.label="Classification",
  VAR.main.label="",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Percent of Obligations",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(full_data,Theater!="Unlabeled"),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="NIAcrisisFunding", #VAR.y.series
  VAR.facet.primary= "Theater", #VAR.facet.primary
  # VAR.facet.secondary="contingencyhumanitarianpeacekeepingoperationText", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+theme(legend.position="bottom")+
  scale_x_date(
            # breaks=date_breaks("5 years"),
            labels=date_format("'%y"))


  
full_data$NIAcontradictions<-full_data$NIAcrisisFunding
full_data$NIAcontradictions<-factor(full_data$NIAcontradictions,
                                    levels=c("Disaster",
                                             "OCO",
                                             "Missed OCO",
                                             "Unlabeled"
                                             )
                                    )
full_data$NIAcontradictions[full_data$NIAcrisisFunding=="Unlabeled" & 
                              full_data$CrisisFunding=="OCO" ]<-"Missed OCO"

unique(subset(full_data,NIAcontradictions!="Unlabeled"
              & Fiscal.Year<=as.Date("2008-01-01"))$nationalinterestactioncodeText)


Tree1CisDefense<-LatticePlotWrapper(
  VAR.color.legend.label="Classification Through Step 1B",
  VAR.main.label="",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(full_data,NIAcontradictions!="Unlabeled"),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="CrisisFunding", #VAR.y.series
  VAR.facet.primary= "NIAcontradictions", #VAR.facet.primary
  VAR.facet.secondary="Is.Defense", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
              , scales="fixed" #The scales actually do stay fixed
              , space="fixed")+theme(legend.position="bottom")
  


Tree1Coco<-LatticePlotWrapper(
  VAR.color.legend.label="National Interest Action",
  VAR.main.label="",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(full_data,NIAcrisisFunding=="OCO" | (CrisisFunding=="OCO" & nationalinterestactioncodeText=="None")),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="CrisisFunding", #VAR.y.series
  VAR.facet.primary= "nationalinterestactioncodeText", #VAR.facet.primary
  # VAR.facet.secondary="Theater", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_wrap(~primary,ncol=3)
# +facet_grid(primary ~ secondary
#               , scales="free_y" #The scales actually do stay fixed
#               , space="fixed")


  #NIAcrisisFunding
Tree1Ctheater
Tree1CisDefense
Tree1Coco
Tree1CdetailIsDefense
ggsave("Output//Tree1CisDefense.png", Tree1CisDefense, width=6.5, height= 3, units="in",dpi=300)
ggsave("Output//Tree1CdetailIsDefense.png", Tree1CdetailIsDefense , width=4, height= 5, units="in",dpi=300)

ggsave("Output//Tree1Coco.png", Tree1Coco, width=6.5, height= 3, units="in",dpi=300)

#Apply decisions
full_data$CrisisFunding[full_data$CrisisFunding=="Unlabeled" & full_data$NIACcrisisFunding=="OCO"]<-"OCO"
full_data$CrisisFunding[full_data$CrisisFunding=="Unlabeled" & full_data$NIACcrisisFunding=="Disaster"]<-"Disaster"

save(full_data,file="LargeDataSets//full_data_after_step_1C.Rdata")

```


##Step 1D: Revealing Waivers to the CCR Reporting Requirement
```{r Step1D}
# CCRexception 

Tree1DisDefense<-LatticePlotWrapper(
  VAR.color.legend.label="Classification Through Step 1C",
  VAR.main.label="",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(full_data,SAMexception.sum!="No Exception"),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="CrisisFunding", #VAR.y.series
  VAR.facet.primary= "SAMexception.sum", #VAR.facet.primary
  VAR.facet.secondary="Is.Defense", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
              , scales="free_y" #The scales actually do stay fixed
              , space="fixed")+theme(legend.position="bottom")

Tree1DisDefense
summary(full_data$CCRexception)
summary(full_data$CCRexception)

plyr::ddply(full_data,
       plyr::.(CCRexception),
       plyr::summarise,
           Obligation.2016=sum(Obligation.2016)
       )

sum(full_data$Obligation.2016[full_data$CCRexception %in% c(3,4)])
```

#Step 2: Iraq and Afghanistan


```{r Step1D}
debug(LatticePlotWrapper)
Tree2isDefense<-LatticePlotWrapper(
  VAR.color.legend.label="Classification Through Step 1B",
  VAR.main.label="",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(full_data,Theater=="Afghanistan and Iraq"),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="CrisisFunding", #VAR.y.series
  VAR.facet.primary= "Is.Defense", #VAR.facet.primary
  # VAR.facet.secondary="Is.Defense", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)
# +facet_grid(primary 
#               , scales="free_y" #The scales actually do stay fixed
#               , space="fixed")+theme(legend.position="bottom")
# 

Tree2isDefense
```


#Trimming this away
```{r Step1}



#Is OCO Crisis Funding
LatticePlotWrapper(
  VAR.color.legend.label="IsOCOcrisisFunding",
  VAR.main.label="Labeled Theater Defense Contracts",
  VAR.X.label="Theater",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=defense_data,
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="IsOCOcrisisFunding", #VAR.y.series
  VAR.facet.primary= "IsOCOcrisisFunding", #VAR.facet.primary
  VAR.facet.secondary="Theater", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
                                              # , labeller=Label_Wrap
              , scales="free_y" #The scales actually do stay fixed
              , space="fixed")

LatticePlotWrapper(
  VAR.color.legend.label="FUll Data CrisisFunding",
  VAR.main.label="Labeled Theater Defense Contracts",
  VAR.X.label="Theater",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=full_data,
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="CrisisFunding", #VAR.y.series
  VAR.facet.primary= "CrisisFunding", #VAR.facet.primary
  VAR.facet.secondary="Theater", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
                                              # , labeller=Label_Wrap
              , scales="free_y" #The scales actually do stay fixed
              , space="fixed")


#Just NIAcrisisFunding
LatticePlotWrapper(
  VAR.color.legend.label="NIAcrisisFunding",
  VAR.main.label="Labeled Theater Defense Contracts",
  VAR.X.label="Theater",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=full_data,
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="NIAcrisisFunding", #VAR.y.series
  VAR.facet.primary= "NIAcrisisFunding", #VAR.facet.primary
  VAR.facet.secondary="Theater", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
                                              # , labeller=Label_Wrap
              , scales="free_y" #The scales actually do stay fixed
              , space="fixed")



#Just NIAcrisisFunding
LatticePlotWrapper(
  VAR.color.legend.label="NIAcrisisFunding",
  VAR.main.label="Labeled Theater Defense Contracts",
  VAR.X.label="Theater",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=full_data,
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="NIAcrisisFunding", #VAR.y.series
  VAR.facet.primary= "NIAcrisisFunding", #VAR.facet.primary
  VAR.facet.secondary="Theater", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
                                              # , labeller=Label_Wrap
              , scales="free_y" #The scales actually do stay fixed
              , space="fixed")



#Just CrisisFunding
LatticePlotWrapper(
  VAR.color.legend.label="OCO labeling detail",
  VAR.main.label="Labeled Theater Defense Contracts",
  VAR.X.label="Theater",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=defense_data,
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="CrisisFunding", #VAR.y.series
  VAR.facet.primary= "CrisisFunding", #VAR.facet.primary
  VAR.facet.secondary="Theater", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+facet_grid(primary ~ secondary
              , scales="free_y" #The scales actually do stay fixed
              , space="fixed")




LatticePlotWrapper(
  VAR.color.legend.label="OCO labeling detail",
  VAR.main.label="Labeled Theater Defense Contracts",
  VAR.X.label="Theater",
  VAR.Y.label="Constant ($ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(defense_data,Theater!='Domestic'),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligation.2016", #VAR.y.variable
  VAR.y.series="IsOCOcrisisFunding", #VAR.y.series
  VAR.facet.primary= "IsOCOcrisisFunding", #VAR.facet.primary
  VAR.facet.secondary="Theater", # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)

# defense_data$ContractCrisisFunding
```

##Points
```{r Points}

Evaluation<-ddply(full_data,
                  .(
                    IsOCOcrisisFunding,
                    OCOcrisisScore,
                    Theater
                  ),
                  plyr::summarise,
                  Obligations=sum(Obligation.2015)
)


Evaluation<-ddply(Evaluation,
                  .(
                    OCOcrisisScore,
                    Theater
                  ),
                  plyr::mutate,
                  pObligations=Obligations/sum(Obligations)
)


LatticePlotWrapper(
  VAR.color.legend.label="OCO labeling detail",
  VAR.main.label="Labeled Theater Defense Contracts",
  VAR.X.label="Theater",
  VAR.Y.label="Percent of Obligations That Are Confirmed OCO",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(Evaluation,IsOCOcrisisFunding=="OCO" & !is.na(Theater)),
  # NA, #VAR.ncol
  VAR.x.variable="Theater", #VAR.x.variable
  VAR.y.variable="pObligations", #VAR.y.variable
  VAR.y.series="Theater", #VAR.y.series
  VAR.facet.primary="OCOcrisisScore" #VAR.facet.primary
  # VAR.facet.secondary= NULL # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  ,DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+  facet_wrap(  ~ primary
                 , nrow=2)+
  scale_y_continuous("Percent of Obligations",
                     labels = scales::percent)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))




Points<-ddply(full_data,
              .(
                Fiscal.Year,
                IsOCOcrisisFunding,
                OCOscoreBuckets
              ),
              plyr::summarise,
              Obligations=sum(Obligation.2015)
)


Points<-ddply(Points,
              .(
                Fiscal.Year,
                IsOCOcrisisFunding
              ),
              plyr::mutate,
              pObligations=Obligations/sum(Obligations)
)


LatticePlotWrapper(
  VAR.color.legend.label="OCO labeling detail",
  VAR.main.label="Defense Contracts",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Percent of Obligations",
  VAR.Coloration=Coloration,
  VAR.long.DF=Points,
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="pObligations", #VAR.y.variable
  VAR.y.series="OCOscoreBuckets", #VAR.y.series
  VAR.facet.primary="IsOCOcrisisFunding" #VAR.facet.primary
  # VAR.facet.secondary= NULL # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  ,DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+ scale_y_continuous("Percent of Obligations",
                      labels = scales::percent)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

PointsRegion<-ddply(full_data,
                    .(
                      Fiscal.Year,
                      IsOCOcrisisFunding,
                      OCOscoreBuckets,
                      Theater
                    ),
                    plyr::summarise,
                    Obligations=sum(Obligation.2015)
)

PointsRegion<-ddply(PointsRegion,
                    .(
                      Fiscal.Year,
                      IsOCOcrisisFunding,
                      Theater
                    ),
                    plyr::mutate,
                    pObligations=Obligations/sum(Obligations)
)

PointsRegion$OCOscoreBuckets<-ordered(PointsRegion$OCOscoreBuckets)

LatticePlotWrapper(
  VAR.color.legend.label="OCO labeling detail",
  VAR.main.label="Defense Contracts",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Percent of Obligations",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(PointsRegion,!is.na(Theater)),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="pObligations", #VAR.y.variable
  VAR.y.series="OCOscoreBuckets", #VAR.y.series
  VAR.facet.primary="IsOCOcrisisFunding", #VAR.facet.primary
  VAR.facet.secondary= "Theater" # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  ,DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+ scale_y_continuous("Percent of Obligations",
                      labels = scales::percent)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))



```



##Labeling
```{r Labeling}

full_data$OCOlabelDetail<-full_data$OCOscoreBuckets
levels(full_data$OCOlabelDetail) <- 
  c(levels(full_data$OCOlabelDetail),"Confirmed OCO")
full_data$OCOlabelDetail[full_data$CrisisFunding=="OCO"]<-"Confirmed OCO"


full_data$IsCSISOCO<-"All Other"
full_data$IsCSISOCO[full_data$CrisisFunding=="OCO"|full_data$OCOcrisisScore>=6]<-"Confident OCO"







Dollars<-ddply(full_data,
               .(
                 Fiscal.Year,
                 OCOlabelDetail,
                 IsCSISOCO
               ),
               plyr::summarise,
               Obligations=sum(Obligation.2015)
)



LatticePlotWrapper(
  VAR.color.legend.label="OCO labeling detail",
  VAR.main.label="All Defense Contracts",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Obligations (2015 $ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=Dollars,
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligations", #VAR.y.variable
  VAR.y.series="OCOlabelDetail", #VAR.y.series
  VAR.facet.primary="IsCSISOCO" #VAR.facet.primary
  # VAR.facet.secondary= NULL # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  ,DataLabels=FALSE
  #                       ,VAR.override.coloration=NA
)+theme(legend.position="bottom")



DollarsTheater<-ddply(full_data,
                      .(
                        Fiscal.Year,
                        OCOlabelDetail,
                        IsCSISOCO,
                        Theater
                      ),
                      plyr::summarise,
                      Obligations=sum(Obligation.2015)
)


full_data[full_data$PlaceCountryText %in% c("Jordan","Turkey"),]



LatticePlotWrapper(
  VAR.color.legend.label="OCO labeling detail",
  VAR.main.label="Defense Contracts with Labeled Theater",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Obligations (2015 $ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(DollarsTheater,!is.na(Theater)),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligations", #VAR.y.variable
  VAR.y.series="OCOlabelDetail", #VAR.y.series
  VAR.facet.primary="Theater", #VAR.facet.primary
  VAR.facet.secondary="IsCSISOCO" # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  # ,DataLabels=NA
  #                       ,VAR.override.coloration=NA
)+theme(legend.position="right")


DollarsInternational<-ddply(full_data,
                            .(
                              Fiscal.Year,
                              OCOlabelDetail,
                              IsCSISOCO,
                              International
                            ),
                            plyr::summarise,
                            Obligations=sum(Obligation.2015)
)


full_data[full_data$PlaceCountryText %in% c("Jordan","Turkey"),]




OCOdetail<-LatticePlotWrapper(
  VAR.color.legend.label="OCO labeling detail",
  VAR.main.label="Defense Contracts with Labeled Location",
  VAR.X.label="Fiscal Year",
  VAR.Y.label="Obligations (2015 $ Billions)",
  VAR.Coloration=Coloration,
  VAR.long.DF=subset(DollarsInternational,!is.na(International)),
  # NA, #VAR.ncol
  VAR.x.variable="Fiscal.Year", #VAR.x.variable
  VAR.y.variable="Obligations", #VAR.y.variable
  VAR.y.series="OCOlabelDetail", #VAR.y.series
  VAR.facet.primary="International", #VAR.facet.primary
  VAR.facet.secondary="IsCSISOCO" # VAR.facet.secondary=NA
  # ,MovingAverage=0
  # ,MovingSides=1
  # ,DataLabels=NA
  #                       ,VAR.override.coloration=NA
)

OCOdetail+theme(legend.position="right")

```